package main
/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

import (
   "fmt"
)

func main() {
   sum := 2
   l := 2
   c := 3
   new := 0
   for c < 4000000 {
      new = l + c
      l = c
      c = new
      if c % 2 == 0 {
        sum+=c
      }
   }
   fmt.Println(sum)
}
