// ProjectEuler.net - Problem 29 (Distinct Powers)
// How many distinct terms are in the sequence generated by
// a^b for 2 <= a <= 100 and 2 <= b <= 100?

package main

import (
   "fmt"
   "math/big"
)

var terms map[string]int

func main() {
   terms = make(map[string]int)
   exp := big.NewInt(0)
   for x := 2 ; x <= 100; x++ {
      for y := 2 ; y <= 100; y++ {
          t := exp.Exp(big.NewInt(int64(x)),big.NewInt(int64(y)),nil)
          terms[t.String()]++
      }
   }
   n := len(terms)
   fmt.Printf("Number of Distinct Terms: %d\n", n)
}
